### PR TITLE
SUP-1460 Fix provider_settings validation

### LINKED ISSUE #409: provider_settings validation fails when respository is dynamic
**Describe the bug**
When using the resource `buildkite_pipeline` in a module with a repository containing variable interpolation, the validation of the `provider_settings` fails

**To Reproduce**

A small reproducer
```
resource "buildkite_pipeline" "main" {
  name        = var.name
  repository  = "git@github.com:${var.repository}.git"

  provider_settings = {
    trigger_mode = "code"
  }
}
```

Trigger this output 
```
╷
│ Error: Could not parse repository URL
│ 
│   with module.agent_release.buildkite_pipeline.main,
│   on modules/buildkite_release/main.tf line 3, in resource "buildkite_pipeline" "main":
│    3: resource "buildkite_pipeline" "main" {
│ 
╵
╷
│ Error: Invalid attribute value
│ 
│   with module.agent_release.buildkite_pipeline.main,
│   on modules/buildkite_release/main.tf line 3, in resource "buildkite_pipeline" "main":
│    3: resource "buildkite_pipeline" "main" {
│ 
│ Invalid use when repository is: 
╵
```

**Additional context**

terraform-provider-buildkite Version 1.0

Probably introduced in https://github.com/buildkite/terraform-provider-buildkite/pull/387/files

### LINKED ISSUE #410: Provider errors upgrading from 0.27.0 to 1.0.0
**Describe the bug**
I'm using a modular approach to defining my pipelines and I'm getting a high number of errors for instances of the module when I move my provider version from 0.27.0 to 1.0.0 and follow the upgrade steps.

On `plan`, for each instance of the module, I see:

```
│ Error: Invalid attribute value
│
│   with buildkite_pipeline.pipeline["persona-identity"],
│   on main.tf line 1, in resource "buildkite_pipeline" "pipeline":
│    1: resource "buildkite_pipeline" "pipeline" {
│
│ Invalid use when repository is: git@bitbucket.org:persona-id/persona-identity.git
```

And:

```
│ Error: Invalid Attribute Value
│
│   with buildkite_pipeline.pipeline["persona-identity"],
│   on main.tf line 1, in resource "buildkite_pipeline" "pipeline":
│    1: resource "buildkite_pipeline" "pipeline" {
│
│ Attribute provider_settings.pull_request_branch_filter_enabled true, got: false
```

In the plan output. I get both errors for every instance of the module.

**To Reproduce**

Here is my modular definition block:

```
resource "buildkite_pipeline" "pipeline" {
  # See: https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/resources/pipeline
  for_each = local.pipelines

  # Required settings
  default_branch = each.value.default_branch
  description    = each.value.description
  name           = each.key
  repository     = each.value.repository

  # Immutable settings
  steps = lookup(each.value, "custom_steps", lookup(each.value, "deflake_mode", false) ? file("./deflake-steps.yaml") : file("./default-steps.yaml"))

  # Optional settings
  allow_rebuilds             = lookup(each.value, "allow_rebuilds", true)
  branch_configuration       = lookup(each.value, "branch_configuration", "")
  default_timeout_in_minutes = lookup(each.value, "default_timeout_in_minutes", 0)
  maximum_timeout_in_minutes = lookup(each.value, "maximum_timeout_in_minutes", 0)
  tags                       = lookup(each.value, "tags", [])

  skip_intermediate_builds                 = lookup(each.value, "only_build_latest_branch", lookup(each.value, "skip_intermediate_builds", true))
  skip_intermediate_builds_branch_filter   = lookup(each.value, "only_build_latest_branch_filter", lookup(each.value, "skip_intermediate_builds_branch_filter", ""))
  cancel_intermediate_builds               = lookup(each.value, "only_build_latest_branch", lookup(each.value, "cancel_intermediate_builds", true))
  cancel_intermediate_builds_branch_filter = lookup(each.value, "only_build_latest_branch_filter", lookup(each.value, "cancel_intermediate_builds_branch_filter", ""))

  provider_settings = {
    build_branches                           = lookup(each.value, "build_branches", true)
    build_pull_requests                      = lookup(each.value, "build_pull_requests", true)
    build_tags                               = lookup(each.value, "build_tags", false)
    filter_condition                         = lookup(each.value, "filter_condition", "")
    filter_enabled                           = lookup(each.value, "filter_enabled", false)
    publish_commit_status                    = lookup(each.value, "publish_commit_status", true)
    publish_commit_status_per_step           = lookup(each.value, "publish_commit_status_per_step", false)
    pull_request_branch_filter_configuration = lookup(each.value, "pull_request_branch_filter_configuration", "")
    pull_request_branch_filter_enabled = lookup(each.value,
    "pull_request_branch_filter_enabled", false)
    skip_pull_request_builds_for_existing_commits = lookup(each.value, "skip_pull_request_builds_for_existing_commits", true)
  }
}
```

And here are my `variables.tf` for one instance of the module:

```
locals {
  pipelines = {
    "persona-identity" = {
      repository     = "git@bitbucket.org:persona-id/persona-identity.git"
      description    = "Persona Identity Service"
      default_branch = "master"
    },
}
```

**Expected behavior**
Following the upgrade guide, I was expecting a fairly straightforward upgrade to 1.0.0 from 0.27.0. I didn't think any of our structure here was really pushing limits.

**Additional context**
Since we're not actually overriding the default value of `pull_request_branch_filter_enabled` in this instance of the module, I deleted it to see if I could get it to plan/apply. Terraform just complains about one of the other settings in the `provider_settings` block when I do that. Feels like it is not so much about the setting, and more that we're doing a lookup with a default  value for the setting in our case.

### PR DESCRIPTION
**Pull request by jradtilbrook**
## PR checklist:
- [x] `docs/` updated
- [x] tests added
- [x] an example added to `examples/` (useful to demo new field/resource)
- [x] `CHANGELOG.md` updated with pending release information

Fixes #409 
Fixes #410

### CODE REVIEW

File: buildkite/resource_pipeline.go [hunk 1]
```diff
@@ -501,14 +501,11 @@ func (*pipelineResource) Schema(ctx context.Context, req resource.SchemaRequest,
...
+						},
 						Validators: []validator.Bool{
-							boolvalidator.Any(
-								pipelinevalidation.WhenRepositoryProviderIs(pipelinevalidation.RepositoryProviderBitbucket),
-								boolvalidator.All(
-									pipelinevalidation.WhenRepositoryProviderIs(pipelinevalidation.RepositoryProviderGitHub),
-									boolvalidation.WhenString(path.MatchRoot("provider_settings").AtName("trigger_mode"), "code"),
-								),
-							),
+							boolvalidation.WhenString(path.MatchRoot("provider_settings").AtName("trigger_mode"), "code"),
```
Comment (jradtilbrook) [inline buildkite/resource_pipeline.go:508]: This custom validator already only enforces the `code` value when it is set. When this attribute is completely missing from `provider_settings` it doesn't check the value (there isn't one). So since its not a valid value when the repository is hosted on bitbucket, it is safe to keep here since it should not be present at all

**Review by james2791 — APPROVED** [review]
